### ISSUE TITLE
Misc 'run' endpoint errors

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/wt_versioning#14]
This issue is to track a few small issues with the 'run/' endpoint. This issue was origionally about the _checkAccess issue but I modified the title to make it more inclusive for other tiny things.

### AttributeError: AttributeError(\"'Run' object has no attribute '_checkAccess
When posting a new Run, I ran across the following stack trace. I didn't see a method in the parent class for `_checkAccess`, I also thumbed through the Girder API and wasn't able to find a reference for the method in the 'Resource' class. I do know that wt_home_dirs has it defined in a few places though...

To Reproduce:

1. Create a Tale
2. Create a version
3. POST a run for that version
4. See the error message

```
{
  "message": "AttributeError: AttributeError(\"'Run' object has no attribute '_checkAccess'\")",
  "trace": [
    "<FrameSummary file /girder/girder/api/rest.py, line 630 in endpointDecorator>",
    "<FrameSummary file /girder/girder/api/rest.py, line 1227 in POST>",
    "<FrameSummary file /girder/girder/api/rest.py, line 970 in handleRoute>",
    "<FrameSummary file /girder/girder/api/access.py, line 63 in wrapped>",
    "<FrameSummary file /girder/girder/api/rest.py, line 445 in wrapped>",
    "<FrameSummary file /girder/girder/api/describe.py, line 709 in wrapped>",
    "<FrameSummary file /girder/plugins/wt_versioning/server/resources/run.py, line 107 in create>"
  ],
  "type": "internal"
}
```

Edit: The paramType for taleId in the list runs endpoint is a path and should be query

### Typo on AccessType.WRTITE
[This](https://github.com/whole-tale/wt_versioning/blob/master/server/resources/run.py#L130) line has a typo on 'WRITE' that's causing it to fail.

**Comment by Xarthisius** [comment]
That's my doing most certainly (see https://github.com/whole-tale/wt_versioning/pull/13). I was focused on versions, which are part of upcoming release, whereas runs come after that. I can fix it (removing `_checkAccess` call should be sufficient), but this API is not wired into anything right now, i.e. it won't launch a job, won't start a container or anything like that.

**Comment by ThomasThelen** [comment]
No worries-I was playing around with a mockup in the dashboard (all I needed was the run name); I ended up commenting it out for the time being so I think it's fine to leave as-is.

**Comment by bodom0015** [comment]
Revisiting this, since we're discussing this feature again. Not sure how far along the `/run` stuff should be, but figured I should retest these endpoints just to get a lay-of-the-land.

Similar to what Tommy mentioned, I am unable to use any of the current endpoints under `/run`:
* `GET /run` claims to accept a `taleId` as a `path` parameter, but the resulting URL doesn't use the `taleId` that I provide (`https://girder.stage.wholetale.org/api/v1/run?limit=50&sort=created&sortdir=1`) so Girder never receives it: `{  "message": "Parameter \"taleId\" is required.", "type": "rest" }`
* `POST /run` apparently complains about permissions? This might be user-error, as the flow here is a bit confusing. This endpoint accepts a `versionId`, so I look up a Tale that I own and use that `taleId` to fetch a version from the Tale, then turn around and use that version's `versionId` to call `POST /run`, but I receive the following error about permissions: `{ "message": "Admin access denied for folder 608ab72f22bad715637af441 (user None).", "type": "access" }`
* All other endpoints require an `id` that I assume I would receive back from `POST /run`, so I can't test these ones just yet

**Comment by hategan** [comment]
> Not sure how far along the `/run` stuff should be

It shouldn't be doing this. 

I'll take a look if @Xarthisius doesn't beat me to it.

**Comment by Xarthisius** [comment]
Things were broken when we revamped versions during previous release cycle. `/run` endpoints are definitely not ready to be integrated with the UI at this moment. I'm planning to work on it, but I'm blocked by other PRs that need reviews (specifically https://github.com/whole-tale/girder_wholetale/pull/500 which is causing wt_versioning tests to fail.)

**Comment by craig-willis** [comment]
On Jun 23, 2021 12:15 PM, Kacper Kowalik ***@***.***> wrote:

Things were broken when we revamped versions during previous release cycle. /run endpoints are definitely not ready to be integrated with the UI at this moment. I'm planning to work on it, but I'm blocked by other PRs that need reviews (specifically whole-tale/girder_wholetale#500<https://urldefense.com/v3/__https://github.com/whole-tale/girder_wholetale/pull/500__;!!DZ3fjg!uUZkm5liT1wfSO084s0o5HgcyAo5lFEJ1VwQrLT_Va7lBWJA9-2Vx1PA5iX_NwWOW_w$> which is causing wt_versioning tests to fail.)

**Comment by Xarthisius** [comment]
> * `POST /run` apparently complains about permissions? This might be user-error, as the flow here is a bit confusing. This endpoint accepts a `versionId`, so I look up a Tale that I own and use that `taleId` to fetch a version from the Tale, then turn around and use that version's `versionId` to call `POST /run`, but I receive the following error about permissions:

I can't reproduce that. It's being tested right now in https://github.com/whole-tale/wt_versioning/pull/30
and does what you described without any error:
https://github.com/whole-tale/wt_versioning/pull/30/files#diff-61b053eecd2b24a02f7b6675d5e51efdb29cc5b235ce1d05fa4c02525a481afbR40-R56

Could you try out that PR?
